spring:
  application:
    name: spring-ai-intro
  threads:
    virtual:
      enabled: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
  docker:
    compose:
      lifecycle-management: start_only

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
#  atlas:
#    metrics:
#      export:
#        uri: http://localhost:7101/api/v1/publish
#        enabled: true
#        step: 10s