spring:
  application:
    name: spring-ai-intro
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-3-5-sonnet-20240620
          max-tokens: 2000
