spring:
  application:
    name: spring-ai-intro
  threads:
    virtual:
      enabled: true
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model:  llama3-70b-8192
  docker:
    compose:
      lifecycle-management: start_only

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
#  atlas:
#    metrics:
#      export:
#        uri: http://localhost:7101/api/v1/publish
#        enabled: true
#        step: 10s