spring:
  application:
    name: spring-ai-intro
  threads:
    virtual:
      enabled: true
  ai:
    chat:
      client:
        enabled: false

  docker:
    compose:
      lifecycle-management: start_only

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'