spring:
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: openrouter/free
#          model: claude-opus-4-0
